name: Build MongoDB image
permissions:
  contents: read

on:
  push:
    branches:
      - 0.118.0-atlantis
    paths:
      - '.github/workflows/build_mongodb.yaml'
      - 'docker/mongodb/Dockerfile'
  workflow_dispatch:

env:
  IMAGE_TAG: 0.118.0-atlantis
  REF: 0.118.0-atlantis
  EXTRA_TAGS: ""
  PLATFORMS: linux/amd64

jobs:
  build_mongodb:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build_docker.yaml
    with:
      image_file: docker/mongodb/Dockerfile
      image_name: kanisterio/mongodb-yaron
      image_tag: ${{ env.IMAGE_TAG }}
      extra_tags: ${{ env.EXTRA_TAGS }}
      ref:  ${{ env.REF }}
      ## Only amd64 platform is supported
      # platforms: ${{ env.PLATFORMS }}
      platforms: linux/amd64
      build-args: |
        TOOLS_IMAGE=ghcr.io/kanisterio/kanister-tools:${{ env.IMAGE_TAG }}
      labels: |
        org.opencontainers.image.title=kanister mongodb
        org.opencontainers.image.description=Image for kanister mongodb example blueprints