name: Build MongoDB image
permissions:
  contents: read

on:
  push:
    branches:
      - 0.118.0-atlantis
    paths:
      - '.github/workflows/build_mongodb.yaml'
      - 'docker/mongodb/Dockerfile'
  workflow_dispatch:
    inputs:
      image_tag:
        required: false
        type: string
        default: 0.118.0-atlantis
      ref:
        required: false
        type: string
        default: 0.118.0-atlantis
      extra_tags:
        required: false
        type: string
      platforms:
        required: false
        default: linux/amd64
        type: string
  workflow_call:
    inputs:
      image_tag:
        required: false
        type: string
        default: 0.118.0-atlantis
      ref:
        required: false
        type: string
        default: 0.118.0-atlantis
      extra_tags:
        required: false
        type: string
      platforms:
        required: false
        default: linux/amd64
        type: string

jobs:
  build_mongodb:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build_docker.yaml
    with:
      image_file: docker/mongodb/Dockerfile
      image_name: kanisterio/mongodb-yaron
      image_tag: ${{ inputs.image_tag }}
      extra_tags: ${{ inputs.extra_tags }}
      ref:  ${{ inputs.ref }}
      ## Only amd64 platform is supported
      # platforms: ${{ inputs.platforms }}
      platforms: linux/amd64
      build-args: |
        TOOLS_IMAGE=ghcr.io/kanisterio/kanister-tools:${{ inputs.image_tag }}
      labels: |
        org.opencontainers.image.title=kanister mongodb
        org.opencontainers.image.description=Image for kanister mongodb example blueprints